# Generated by Django 3.2 on 2021-07-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='mainapp.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
